### PR TITLE
Fix icon flicker

### LINKED ISSUE #146: Unrelated icons change when extensions are toggled
scroll

Probably due to:

- unintended Svelte state dependency 
- misuse of the icon picker function

### PR DESCRIPTION
**Pull request by hankxdev**
To fix #146 
The reason that some  icon change while toggling the state of other extensions is the use of `reverse` on icon list.

To fix it, use a simple sort function to make sure the order does not change.

### CODE REVIEW

File: source/extension.svelte [hunk 1]
```diff
@@ -57,17 +57,21 @@
 		size *= window.devicePixelRatio;
 
 		if (icons) {
+			const sortedIcons = icons.sort(sortIconBySize);
 			// Get a large icon closest to the desired size
-			for (const icon of icons.reverse()) {
+			for (const icon of sortedIcons) {
```
Comment (fregante) [inline source/extension.svelte:62]: Good catch! We can actually use .toReversed() now

**Review by fregante — CHANGES_REQUESTED** [review]
Actually I don’t think this fixes it. .sort() also alters the array just like .reverse()

- https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1743


.toReversed() will fix it, just need to bump the minimum chrome version to 110

**Review by fregante — APPROVED** [review]
